### ISSUE TITLE
Add support for turning bytes / hashes into hex string

### ISSUE THREAD

**Issue by matiwinnetou** [aiken-lang/stdlib#14]
Aiken git hash: [0e65fecf698c864349e1f6ec757d258a0ad63f43](https://github.com/aiken-lang/aiken/commit/0e65fecf698c864349e1f6ec757d258a0ad63f43)

It seems that serialising Hash<Blake2b_256, String> into string fails in Aiken.

1)  let v: String = "leaf1"
2) let h: Hash<Blake2b_256, String> = hash.blake2b_256(bytearray.from_string(v))
3) let hs: String = bytearray.to_string(h)

Ideally I would like to have a function somewhere, maybe in hex.ak
hex.to_string(b: ByteArray) -> String

**Comment by KtorZ** [comment]
Could you elaborate on how exactly it fails?

I don't think you'll ever want to encode a string to base16 **on-chain**. Base16 is a textual representation used for manipulating binary data in console, urls, files etc.. In a program, you're usually dealing with byte arrays. Perhaps you could explain a bit more your use case 🤔 ?

**Comment by matiwinnetou** [comment]
My use-case is only for debuggability. It is easier to send somebody hex string than byte array and it can be human readable.

**Comment by KtorZ** [comment]
Hmm. Sure but, why would you compute the hex string directly in the Plutus' runtime? This is really not something we ought to support. 

The parser already provides some syntactic sugar to parse a literal base16-encoded string into a ByteArray. We could try to have the UPLC interpreter outputs byte arrays as base16-encoded strings (though I am surprised that this isn't already the behavior). Having a better understanding of the error you're facing would help.

**Comment by matiwinnetou** [comment]
The error is that Aiken compiler throws an error, blows up on line 3

**Comment by KtorZ** [comment]
What error, please.

**Comment by matiwinnetou** [comment]
Unfortunately error is not provided, so I had to run aiken check --debug.

```
  × first_test failed
  │ (program
  │   1.0.0
  │   [
  │     (lam
  │       v
  │       [
  │         (lam
  │           vb
  │           [
  │             (lam
  │               h
  │               [
  │                 (lam _ (con bool True))
  │                 [
  │                   (lam
  │                     aiken/bytearray_to_string
  │                     [ aiken/bytearray_to_string h ]
  │                   )
  │                   (lam self [ (builtin decodeUtf8) self ])
  │                 ]
  │               ]
  │             )
  │             [
  │               (lam aiken/hash_blake2b_256 [ aiken/hash_blake2b_256 vb ])
  │               (lam bytes [ (builtin blake2b_256) bytes ])
  │             ]
  │           ]
  │         )
  │         [
  │           (lam aiken/bytearray_from_string [ aiken/bytearray_from_string v ])
  │           (lam str [ (builtin encodeUtf8) str ])
  │         ]
  │       ]
  │     )
  │     (con string "leaf1")
  │   ]
  │ )
```

**Comment by KtorZ** [comment]
(@matiwinnetou `main` is now fixed and can now correctly parse base16 literals in expressions too.

**Comment by KtorZ** [comment]
Does that solve your problem?

**Comment by matiwinnetou** [comment]
As I said it was only for debugging but I stumbled upon this.

Thank You so much. Will test and close if it works against main branch (see no reason why it should not, just double check).
