### ISSUE TITLE
cbor diagnostic  on OutputReference does not include output index

### ISSUE THREAD

**Issue by MicroProofs** [aiken-lang/stdlib#32]
When using diagnostic on output reference I get 
121([_ 121([_ h'4D268FB8390F468B452EE1723A39655E1D097D4CD0B1E4DFE7B9C626D3B55BB0']), ])
as the trace. I think the issue is diagnostic ignores the second constr field.

**Comment by KtorZ** [comment]
Funnily enough, the issue wasn't on the constr variant, but on how integers are turned to string. More specifically, the integer `0` should simply be omitted if nested into some other structure. Now fixed :)
