### ISSUE TITLE
Suggested function: bytearray.to_hex / bytearray.from_hex

### ISSUE THREAD

**Issue by Quantumplation** [aiken-lang/stdlib#49]
When debugging, it'd be super helpful to be able to hex-encode a bytearray so I can pass it to `trace`; You might just say use cbor.diagnostic, but I prefer the hex view over cbor.diagnostic.

There may be other use cases, though not many come to mind.

**Comment by Quantumplation** [comment]
(feel free to close if you feel this is out of scope, just dropping the suggestion here while it's on my mind)

**Comment by KtorZ** [comment]
Honestly. `from_hex` is going to be a pain in the a** on chain, especially without bitwise primitives. Though writing an encoder may be more reasonable. Actually, so "reasonable" that we already did it 😬!  

https://github.com/aiken-lang/stdlib/blob/a467c812f9575c500eb78b2e3a2214e24c17e024/lib/aiken/cbor.ak#L212-L237

So I guess it's mainly about moving that function to the `bytearray` module

**Comment by rvcas** [comment]
@KtorZ I have a little example
