### ISSUE TITLE
Wrong example in docs

### ISSUE THREAD

**Issue by ariady-putra** [aiken-lang/stdlib#54]
`List.reduce` **example-arguments** are flipped:
https://aiken-lang.github.io/stdlib/aiken/list.html#reduce
> ```gleam
> reduce(self: List<a>, zero: b, with: fn(b, a) -> b) -> b
> ```
> Reduce a list from left to right using the accumulator as left operand. Said differently, this is [foldl](https://aiken-lang.github.io/stdlib/aiken/list.html#foldl) with callback arguments swapped.
> ```gleam
> list.reduce([#[1], #[2], #[3]], bytearray.concat, #[0]) == #[0, 1, 2, 3]
> list.reduce([True, False, True], fn(b, a) { or([b, a]) }, False) == True
> ```
It should be:
> ```gleam
> list.reduce([#[1], #[2], #[3]], #[0], bytearray.concat) == #[0, 1, 2, 3]
> list.reduce([True, False, True], False, fn(b, a) { or([b, a]) }) == True
> ```
https://github.com/aiken-lang/stdlib/blob/c42b6137f9325647096a2b3b5f819b80c0268557/lib/aiken/list.ak#L1336

**Comment by rvcas** [comment]
Ah yes, we had switched the arguments in the definitions last release, thanks for pointing this out
