### ISSUE TITLE
Introduction of `trace_if_false`

### ISSUE THREAD

**Issue by KristianBalaj** [aiken-lang/stdlib#55]
What are your opinions on introduction of `trace_if_false`? It's heavily inspired by Plutus but I think it's an important function.
In my opinion, it's important to have traces for each predicate in validator.

It could be an addition in the `stdlib` like the following:
```
fn trace_if_false(str: String, res: Bool) {
  if !res {
    trace str
    res
  } else {
    res
  }
}
```

But I think it adds unnecessary condition in the exported UPLC when having traces off? So maybe it would make more sense to have some keyword on the language level?

This proposal could also be seen in the same bucket for better developer experience https://github.com/aiken-lang/aiken/issues/489#issuecomment-1584305945

**Comment by KtorZ** [comment]
Aiken provides this as a built in operator already: https://aiken-lang.org/language-tour/troubleshooting#-operator

**Comment by KristianBalaj** [comment]
@KtorZ yes, I'm aware it's available, but I'm interested in providing custom trace messages, having a trace from the code is not that great IMHO.

**Comment by rvcas** [comment]
@KristianBalaj 

you can use `aiken/builtin` to make your own utility and publish it as a package on github. This then doesn't need to dependent on stdlib.

```
use aiken/builtin

fn trace_if_false(message: String, expr: Bool) -> Bool {
  if expr {
    expr
  } else {
    builtin.debug(message, expr)
  }
} 
```
